# Generated by Django 4.2.30 on 2026-04-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Tax Invoice'), ('proforma', 'Pro Forma Invoice'), ('quotation', 'Quotation')], default='invoice', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
