# Generated by Django 5.0.6 on 2026-06-18 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_document_type_invoice_valid_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(help_text='e.g., "SACCOS Interest", "Landlord Grant"', max_length=150)),
                ('category', models.CharField(choices=[('interest', 'Interest Income'), ('dividend', 'Dividend'), ('gift', 'Gift/Donation'), ('grant', 'Grant'), ('rental', 'Rental Income'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('income_date', models.DateField(help_text='Date income was received')),
                ('collection_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], default='bank_transfer', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='e.g., transaction ID, check number', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional details about the income')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-income_date'],
                'indexes': [models.Index(fields=['-income_date'], name='billing_oth_income__597468_idx'), models.Index(fields=['category'], name='billing_oth_categor_3519f2_idx')],
            },
        ),
    ]
