# Generated by Django 5.0.6 on 2026-07-29 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_otherincome'),
        ('core', '0013_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.branch'),
        ),
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.branch'),
        ),
    ]
