# Generated by Django 4.2.30 on 2026-04-16 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_deadline', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='clients.client')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype')),
            ],
            options={
                'unique_together': {('client', 'service_type')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('filed', 'Filed'), ('overdue', 'Overdue'), ('penalty_issued', 'Penalty Issued'), ('waived', 'Waived')], default='upcoming', max_length=20)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('penalty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.jobcard')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='compliance.complianceobligation')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('obligation', 'period_label')},
            },
        ),
    ]
