# Generated by Django 4.2.30 on 2026-04-17 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_invoice_document_type_invoice_valid_until"),
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancedeadline",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="compliancedeadline",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("filed_and_paid", "Filed and Paid"),
                    ("filed_not_paid", "Filed and Not Paid"),
                    ("paid_not_filed", "Paid but Not Filed"),
                    ("none", "None"),
                    ("overdue", "Overdue"),
                    ("penalty_issued", "Penalty Issued"),
                    ("waived", "Waived"),
                ],
                default="upcoming",
                max_length=20,
            ),
        ),
    ]
