# Generated by Django 5.2.13 on 2026-06-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_compliancedeadline_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedeadline',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('filed_and_paid', 'Filed and Paid'), ('filed_not_paid', 'Filed and Not Paid'), ('paid_not_filed', 'Paid but Not Filed'), ('overdue', 'Overdue'), ('penalty_issued', 'Penalty Issued'), ('waived', 'Waived')], default='upcoming', max_length=20),
        ),
    ]
