# Generated by Django 4.2.30 on 2026-04-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notify',
            field=models.EmailField(blank=True, help_text='Email used for sending communications (e.g. taxissues.go@gmail.com)', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_debt_alerts',
            field=models.BooleanField(default=True, help_text='Receive Saturday/Monday debt reports'),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_task_reminders',
            field=models.BooleanField(default=True, help_text='Receive reminders for incomplete tasks'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number used for sending reminders (e.g. +256785230670)', max_length=20),
        ),
    ]
