# Generated by Django 4.2.30 on 2026-04-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_ui_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ui_theme',
            field=models.CharField(
                choices=[
                    ('classic', 'Classic Blue'),
                    ('forest', 'Forest Ledger'),
                    ('sunset', 'Sunset Copper'),
                    ('midnight', 'Midnight Slate'),
                    ('dark', 'Dark Mode'),
                ],
                default='classic',
                max_length=20,
            ),
        ),
    ]
