# Generated by Django 4.2.13 on 2026-04-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_ui_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ui_theme",
            field=models.CharField(
                choices=[
                    ("system", "System Default"),
                    ("classic", "Classic Blue"),
                    ("forest", "Forest Ledger"),
                    ("sunset", "Sunset Copper"),
                    ("midnight", "Midnight Slate"),
                    ("dark", "Dark Mode"),
                    ("ocean", "Ocean Teal"),
                    ("rose", "Rose Gold"),
                    ("charcoal", "Charcoal Pro"),
                    ("violet", "Violet Dusk"),
                    ("earth", "Earth Brown"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
