# Generated by Django 5.2.13 on 2026-05-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_user_ui_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ui_theme",
            field=models.CharField(
                choices=[("ocean", "Ocean Teal")], default="ocean", max_length=20
            ),
        ),
    ]
