# Generated by Django 6.0.6 on 2026-06-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_reporting_models'),
        ('core', '0007_company_user_company'),
    ]

    operations = [
    ]
