# Generated by Django 6.0.6 on 2026-06-11 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0009_add_company_db_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, help_text='Optional description for admin', max_length=255)),
            ],
            options={
                'verbose_name': 'Model Visibility',
                'verbose_name_plural': 'Model Visibilities',
            },
        ),
        migrations.RenameIndex(
            model_name='monthlytrenddata',
            new_name='core_monthl_company_52c092_idx',
            old_name='core_monthly_company_idx',
        ),
        migrations.RenameIndex(
            model_name='transactioneditlog',
            new_name='core_transa_transac_1c0a01_idx',
            old_name='core_transa_transac_idx',
        ),
        migrations.RenameIndex(
            model_name='transactioneditlog',
            new_name='core_transa_client__08f782_idx',
            old_name='core_transa_client__idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='ui_theme',
            field=models.CharField(choices=[('ocean', 'Ocean Teal'), ('dark', 'Dark Mode')], default='ocean', max_length=20),
        ),
        migrations.AddField(
            model_name='modelvisibility',
            name='content_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visibility', to='contenttypes.contenttype'),
        ),
    ]
