# Generated by Django 5.0.6 on 2026-07-29 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_company', to='core.branch'),
        ),
    ]
