# Generated by Django 5.2.13 on 2026-08-01 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_systemmodulevisibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmodulevisibility',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_visibilities', to='core.company'),
        ),
        migrations.AlterField(
            model_name='systemmodulevisibility',
            name='key',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='systemmodulevisibility',
            unique_together={('company', 'key')},
        ),
    ]
