# Generated by Django 6.0.6 on 2026-06-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='approval_required',
            field=models.BooleanField(default=True, help_text='Require approval for expenses in this category'),
        ),
        migrations.CreateModel(
            name='ExpenseApprovalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve_under_amount', models.DecimalField(decimal_places=2, default=0, help_text='Auto-approve expenses under this amount (0 = disabled)', max_digits=12)),
                ('require_receipt_under_amount', models.DecimalField(decimal_places=2, default=100000, help_text='Require receipt upload for expenses above this amount', max_digits=12)),
                ('auto_approve_expense_categories', models.ManyToManyField(blank=True, help_text='Categories that are auto-approved regardless of amount', related_name='auto_approve_settings', to='expenses.expensecategory')),
            ],
            options={
                'verbose_name_plural': 'Expense Approval Settings',
            },
        ),
    ]
