# Generated by Django 4.2.30 on 2026-04-16 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('period_month', models.IntegerField(blank=True, null=True)),
                ('period_year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending_payment', 'Pending Payment'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_periodic', models.BooleanField(default=False)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_cards', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ura_filing', 'URA Filing'), ('nssf', 'NSSF'), ('ursb', 'URSB'), ('ura_advisory', 'URA Advisory'), ('immigration', 'Immigration'), ('customs', 'Customs'), ('advisory', 'Advisory'), ('miscellaneous', 'Miscellaneous')], max_length=30)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deadline_type', models.CharField(choices=[('monthly_15', '15th of Following Month'), ('annual_dec31', 'Annual — 31 December'), ('annual_jun30', 'Annual — 30 June'), ('annual_ursb', 'URSB Annual (12 months from incorporation)'), ('none', 'No Fixed Deadline')], default='none', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('vat_applicable', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='services.jobcard')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCardLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_description', models.CharField(blank=True, max_length=300)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('negotiated_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('handled_paid', 'Handled & Paid'), ('handled_not_paid', 'Handled — Awaiting Payment'), ('not_handled', 'Not Yet Handled')], default='not_handled', max_length=20)),
                ('period_label', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='services.jobcard')),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='ClientServiceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negotiated_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='clients.client')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype')),
            ],
            options={
                'unique_together': {('client', 'service_type')},
            },
        ),
    ]
