# Generated by Django 5.2.13 on 2026-06-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_timeentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardlineitem',
            name='status',
            field=models.CharField(choices=[('handled_paid', 'Handled & Paid'), ('handled_not_paid', 'Handled — Awaiting Payment'), ('paid_not_handled', 'Paid — Not Yet Handled'), ('not_handled', 'Not Yet Handled')], default='not_handled', max_length=20),
        ),
    ]
