# Generated by Django 5.0.6 on 2026-07-29 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_branch'),
        ('services', '0003_alter_jobcardlineitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='core.branch'),
        ),
    ]
