# Generated by Django 4.2.30 on 2026-04-16 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('ura_etax', 'URA e-Tax'), ('nssf', 'NSSF Portal'), ('ursb', 'URSB Portal'), ('bank', 'Bank'), ('mobile_money', 'Mobile Money'), ('customs', 'Customs/ASYCUDA'), ('custom', 'Custom')], max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('username_encrypted', models.TextField(blank=True)),
                ('password_encrypted', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Setup'), ('active', 'Active'), ('needs_reset', 'Needs Reset'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes_encrypted', models.TextField(blank=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credentials', to=settings.AUTH_USER_MODEL)),
                ('last_accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessed_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CredentialAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='credentials.clientcredential')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
    ]
