# Generated by Django 4.2.30 on 2026-04-16 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('client_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('ngo', 'NGO'), ('partnership', 'Partnership')], default='individual', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('trading_name', models.CharField(blank=True, max_length=200)),
                ('tin', models.CharField(blank=True, max_length=50, verbose_name='TIN')),
                ('phone_primary', models.CharField(max_length=20)),
                ('phone_whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('physical_address', models.CharField(blank=True, max_length=300)),
                ('district', models.CharField(default='Kampala', max_length=100)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dormant', 'Dormant'), ('suspended', 'Suspended'), ('blacklisted', 'Blacklisted')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_transaction_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalkInIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('job_created', 'Job Created'), ('declined', 'Declined'), ('referred', 'Referred')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkin_intakes', to='clients.client')),
            ],
        ),
    ]
