# Generated by Django 4.2.13 on 2026-05-01 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="walkinintake",
            name="service_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.servicetype",
            ),
        ),
        migrations.AlterField(
            model_name="walkinintake",
            name="purpose",
            field=models.TextField(blank=True),
        ),
    ]
