# Generated by Django 6.0.5 on 2026-05-28 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_walkinintake_service_type_alter_walkinintake_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10)),
                ('channel', models.CharField(choices=[('call', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('in_person', 'In Person'), ('other', 'Other')], default='call', max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='clients.client')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
