# Generated by Django 5.2.13 on 2026-06-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_communicationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dormant', 'Dormant'), ('suspended', 'Suspended'), ('blacklisted', 'Blacklisted'), ('merged', 'Merged')], default='active', max_length=20),
        ),
    ]
