# Generated by Django 6.0.5 on 2026-05-28 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_communicationlog'),
        ('services', '0002_timeentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('filed_return', 'Filed Return'), ('acknowledgement', 'URA Acknowledgement'), ('source_doc', 'Source Document'), ('correspondence', 'Correspondence'), ('engagement_letter', 'Engagement Letter'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='client_docs/%Y/%m/')),
                ('period_label', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
                ('job_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='services.jobcard')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
