import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE','config.settings')
import django
django.setup()
from django.db import connection
sql = '''
CREATE TABLE IF NOT EXISTS "core_tenant" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "db_alias" varchar(100) NOT NULL, "db_path" varchar(1024) NOT NULL, "status" varchar(20) NOT NULL, "last_error" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "company_id" bigint NOT NULL UNIQUE, "created_by_id" bigint NULL);
ALTER TABLE "core_tenant" ADD CONSTRAINT IF NOT EXISTS "core_tenant_company_id_825d15f6_fk_core_company_id" FOREIGN KEY ("company_id") REFERENCES "core_company" ("id");
ALTER TABLE "core_tenant" ADD CONSTRAINT IF NOT EXISTS "core_tenant_created_by_id_c9f39c01_fk_core_user_id" FOREIGN KEY ("created_by_id") REFERENCES "core_user" ("id");
CREATE INDEX IF NOT EXISTS "core_tenant_created_by_id_c9f39c01" ON "core_tenant" ("created_by_id");
'''
with connection.cursor() as c:
    for stmt in sql.splitlines():
        if stmt.strip():
            try:
                c.execute(stmt)
            except Exception as e:
                print('Error executing:', stmt)
                print(e)
print('Done')
